name: Cron Webhook
on:
  push:
    branches: [ feat/new_indices ]
  schedule:
    - cron: '0 0 * * 1-5'
    - cron: '0 6 * * 1-5'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.11'
    - name: Install dependencies
      run: |
        pip install --upgrade pip
        pip install -r requirements.txt
    - name: Ensure browsers are installed
      run: playwright install --with-deps
    - name: Run main.py
      env:
        WEBHOOK_ID: ${{ secrets.WEBHOOK_ID }}
      run:
        python3 main.py
