name: Cron Webhook
on:
  schedule:
    - cron: '0 0 * * *'
    - cron: '0 6 * * *'
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Set up Python 3.10
      uses: actions/setup-python@v3
      with:
        python-version: "3.10"
    - name: Install dependencies
      run:
        pip install -r requirements.txt
    - name: Run main.py
      env:
        WEBHOOK_ID: ${{ secrets.WEBHOOK_ID }}
      run:
        python3 main.py
